# Generated by Django 4.1.2 on 2022-11-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('author_modification', 'Can modify author'),)},
        ),
    ]
